### ISSUE TITLE
Is there any fee to use this module?

### ISSUE THREAD

**Issue by winer328** [wen-moon-ser/moonshot-sdk#18]
I'm using this module for a while.
Working well.
But I worry about this will gets more fee or not.
Could you tell me about this?

**Comment by mavagio** [comment]
hey @winer328 we won't add an extra fee to the module, the moonshot platform fee is fixed in the smart contract this module is simply making it easy for you to interact with the smart contract.
For your sanity, I would recommend you fix the installed version of the package like so: without ^ or ~ signs. 
```JSON
"dependencies": {
     "@wen-moon-ser/moonshot-sdk": "3.0.0"
},
```
This way you make sure you first review the code before installing a new package.

**Comment by winer328** [comment]
Ok.
I understand.
Thanks for your support.
